name: couldai_user_app
description: "An educational app for schools with AI assistance and 3D visualizations."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  flutter_cube: ^0.1.0  # For 3D visualizations

  # Add more dependencies as needed for UI components

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/  # For 3D models
